@startuml
Вы -> Разум : Что меня мотивирует? 
Разум --> Вы : Стимул
Вы -> Совесть : Просьба делать глупости
Совесть --> Вы : Разрешение делать глупости
Вы -> Помощник : Запрос за звук
Помощник --> Вы : Звук
Вы -> Уши : Подражание звуку
Уши --> Вы : Резонанс
Вы -> Музыка : Какие бывают жанры и песни
Музка --> Вы : Список жанров и песен
Вы -> Аудитория : Пение
Аудитория --> Вы : Приятные впечатления
@enduml